Device: cuda
Episodes Per Evaluation: 5
Max Steps: 10000000
Note: None
Project: CoRL2022
Save: test_june18
Seed: 6
Steps Per Episode: 1800
Steps Per Evaluation: 20000
Steps Per Video: 100000
Task: walking
